name: "RouterOS FW vmolnar"
description: "Script for create and update RouterOS FW to block unwanted traffic from risky IP addresses"
version: "1.0.7"
slug: "routeros_fw_vmolnar"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: share
    read_only: False
options:
  host: "192.168.2.1"
  port: "8728"
  user: "api"
  passwd: "api"
schema:
  host: str
  port: str
  user: str
  passwd: str
