---
version: 1.0.0
slug: websupport_dns_mistral
name: Websupport DNS mistral
description: >-
  Dynamic DNS (DDNS) service for Websupport.sk domains with automatic IP updates
url: https://github.com/home-assistant/addons/tree/master/websupport_dns
type: dns
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
image: homeassistant/{arch}-addon-websupport_dns
host_network: true
map:
  - ssl:rw
options:
  api_key: null
  api_secret: null
  domain: null
  subdomains:
    - null
  record_type: A
  ttl: 3600
  update_interval: 10
schema:
  api_key: str
  api_secret: str
  domain: str
  subdomains:
    - str
  record_type: list(A|AAAA)
  ttl: int
  update_interval: int
startup: services
services:
  - update: >-
      Update DNS records immediately
