name: "Websupport DNS"
description: "Automatically update Websupport.sk DNS A records with your public IP"
version: "0.1.0"
slug: "websupport-dns"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
init: false
startup: application
boot: auto
map:
  - type: share
    read_only: false
options:
  api_key: ""
  api_secret: ""
  domain: ""
  subdomains: []
  base_url: "rest.websupport.sk"
  scan_interval: 10
  ttl: 3600
schema:
  api_key: str
  api_secret: password
  domain: str
  subdomains: "list(str)"
  base_url: str
  scan_interval: "int(1,1440)"
  ttl: "int(60,86400)"